---

- name: install dev tools
  yum: name="@Development tools" state=present

- name: install x86 oracle dependencies for 11g
  yum: name={{ item }} state=present
  with_items:
    - binutils.x86_64
    - compat-libstdc++-33.x86_64
    - compat-libstdc++-33.i686
    - elfutils-libelf.x86_64
    - elfutils-libelf-devel.x86_64
    - expat.x86_64 
    - gcc.x86_64
    - gcc-c++.x86_64
    - glibc.i686
    - glibc.x86_64
    - glibc-common
    - glibc-devel
    - glibc-headers
    - libaio.x86_64
    - libaio.i686
    - libaio-devel.i686
    - libaio-devel.x86_64
    - libgcc.i686
    - libgcc.x86_64
    - libstdc++.x86_64
    - libstdc++.i686
    - libstdc++-devel
    - make
    - numactl
    - ksh
    - sysstat.x86_64
    - xorg-x11-xauth.x86_64
  when: oracle_version | regex_replace ('^([0-9]{1,2}.[0-9]{1,}.[0-9]{1,})(.*)$','\g<1>') == "11.2.0"

- name: install x86 oracle dependencies for 12c
  yum: name={{ item }} state=present
  with_items:
    - binutils.x86_64 
    - compat-libcap1.x86_64
    - compat-libstdc++-33.i686 
    - compat-libstdc++-33.x86_64
    - gcc.x86_64 
    - gcc-c++.x86_64 
    - glibc.i686 
    - glibc.x86_64 
    - glibc-devel.i686 
    - glibc-devel.x86_64 
    - ksh
    - libaio.i686 
    - libaio.x86_64 
    - libaio-devel.i686 
    - libaio-devel.x86_64 
    - libgcc.i686 
    - libgcc.x86_64 
    - libstdc++.i686 
    - libstdc++.x86_64 
    - libstdc++-devel.i686 
    - libstdc++-devel.x86_64 
    - libXi.i686 
    - libXi.x86_64 
    - libXtst.i686 
    - libXtst.x86_64 
    - make.x86_64 
    - sysstat.x86_64 
  when: oracle_version | regex_replace ('^([0-9]{1,2}.[0-9]{1,}.[0-9]{1,})(.*)$','\g<1>') == "12.2.0"