---

- name: create initial groups for the oracle user
  group: name={{ item.name }} gid={{ item.id }} state=present
  with_items:
    - "{{ oracle_group }}"
    - "{{ oracle_dba_group }}"

- name: create oracle user
  user: name="{{ item.name }}" group="{{ oracle_group[0].name }}" uid="{{ item.id }}" groups="{{ oracle_dba_group[0].name }}" home="/home/{{ item.name }}" shell=/bin/bash password="{{ oracle_pass }}" append=yes
  with_items: 
    - "{{ oracle_user }}"

- name: set oracle user environment
  lineinfile: dest=/home/{{ oracle_user[0].name }}/.bashrc state=present line="{{ item }}"
  with_items:
    - "export ORACLE_BASE={{ ora_user_env.ORACLE_BASE }}"
#    - "export ORACLE_SID={{ ora_user_env.ORACLE_SID }}"
    - "export ORACLE_UNQNAME={{ ora_user_env.ORACLE_UNQNAME }}"
    - "export ORACLE_HOME={{ ora_user_env.ORACLE_HOME }}"
    - "export PATH=$PATH:$ORACLE_HOME/bin"
    - "export NLS_LANG={{ ora_user_env.NLS_LANG }}"
    - "echo $ORACLE_HOME"